import type { IconType } from 'react-icons';
import {
  TbAlertTriangle,
  TbArchiveOff,
  TbArrowLeft,
  TbArrowRight,
  TbBell,
  TbBolt,
  TbBoxModel,
  TbBrandCss3,
  TbBrandDocker,
  TbBrandFigma,
  TbBrandGit,
  TbBrandGithub,
  TbBrandHtml5,
  TbBrandJavascript,
  TbBrandLaravel,
  TbBrandMongodb,
  TbBrandMysql,
  TbBrandNextjs,
  TbBrandNodejs,
  TbBrandOpenai,
  TbBrandPhp,
  TbBrandPython,
  TbBrandReact,
  TbBrandSupabase,
  TbBrandTailwind,
  TbBrandTypescript,
  TbBrandVue,
  TbBrandVscode,
  TbCertificate,
  TbChevronDown,
  TbCode,
  TbDatabase,
  TbDeviceFloppy,
  TbDownload,
  TbEdit,
  TbEyeOff,
  TbExternalLink,
  TbFolderCode,
  TbGripVertical,
  TbHelpCircle,
  TbInbox,
  TbLayoutDashboard,
  TbLayersIntersect,
  TbLock,
  TbLogout,
  TbMail,
  TbMapPin,
  TbMessageReply,
  TbMenu2,
  TbNotes,
  TbPhoto,
  TbPhotoPlus,
  TbPlus,
  TbRosetteDiscountCheck,
  TbRulerMeasure,
  TbSearch,
  TbSettings,
  TbSparkles,
  TbSquareRoundedPlus,
  TbTerminal2,
  TbTrash,
  TbTypography,
  TbUpload,
  TbUser,
  TbX,
} from 'react-icons/tb';

export const appIconRegistry = {
  add: TbPlus,
  addBox: TbSquareRoundedPlus,
  archive: TbArchiveOff,
  arrowBack: TbArrowLeft,
  arrowForward: TbArrowRight,
  brandCss3: TbBrandCss3,
  brandDocker: TbBrandDocker,
  brandFigma: TbBrandFigma,
  brandGit: TbBrandGit,
  brandGithub: TbBrandGithub,
  brandHtml5: TbBrandHtml5,
  brandJavascript: TbBrandJavascript,
  brandLaravel: TbBrandLaravel,
  brandMongodb: TbBrandMongodb,
  brandMysql: TbBrandMysql,
  brandNextjs: TbBrandNextjs,
  brandNodejs: TbBrandNodejs,
  brandOpenai: TbBrandOpenai,
  brandPhp: TbBrandPhp,
  brandPython: TbBrandPython,
  brandReact: TbBrandReact,
  brandSupabase: TbBrandSupabase,
  brandTailwind: TbBrandTailwind,
  brandTypescript: TbBrandTypescript,
  brandVue: TbBrandVue,
  brandVscode: TbBrandVscode,
  bolt: TbBolt,
  button: TbBoxModel,
  certificate: TbCertificate,
  chevronDown: TbChevronDown,
  close: TbX,
  code: TbCode,
  dashboard: TbLayoutDashboard,
  database: TbDatabase,
  download: TbDownload,
  drag: TbGripVertical,
  edit: TbEdit,
  externalLink: TbExternalLink,
  eyeOff: TbEyeOff,
  folder: TbFolderCode,
  help: TbHelpCircle,
  image: TbPhoto,
  inbox: TbInbox,
  layers: TbLayersIntersect,
  lock: TbLock,
  logout: TbLogout,
  mail: TbMail,
  mapPin: TbMapPin,
  menu: TbMenu2,
  notes: TbNotes,
  notifications: TbBell,
  photoPlus: TbPhotoPlus,
  publish: TbDeviceFloppy,
  reply: TbMessageReply,
  search: TbSearch,
  settings: TbSettings,
  spacer: TbRulerMeasure,
  sparkles: TbSparkles,
  terminal: TbTerminal2,
  title: TbTypography,
  trash: TbTrash,
  upload: TbUpload,
  user: TbUser,
  verified: TbRosetteDiscountCheck,
  warning: TbAlertTriangle,
} as const satisfies Record<string, IconType>;

export type AppIconKey = keyof typeof appIconRegistry;

export const appIconOptions = [
  { value: 'brandReact', label: 'React' },
  { value: 'brandNextjs', label: 'Next.js' },
  { value: 'brandNodejs', label: 'Node.js' },
  { value: 'brandTypescript', label: 'TypeScript' },
  { value: 'brandJavascript', label: 'JavaScript' },
  { value: 'brandTailwind', label: 'Tailwind CSS' },
  { value: 'brandMongodb', label: 'MongoDB' },
  { value: 'database', label: 'PostgreSQL / SQL' },
  { value: 'brandDocker', label: 'Docker' },
  { value: 'brandGit', label: 'Git' },
  { value: 'brandGithub', label: 'GitHub' },
  { value: 'brandSupabase', label: 'Supabase' },
  { value: 'brandMysql', label: 'MySQL' },
  { value: 'brandPython', label: 'Python' },
  { value: 'brandHtml5', label: 'HTML5' },
  { value: 'brandCss3', label: 'CSS3' },
  { value: 'brandOpenai', label: 'OpenAI' },
  { value: 'brandPhp', label: 'PHP' },
  { value: 'brandLaravel', label: 'Laravel' },
  { value: 'brandVue', label: 'Vue.js' },
  { value: 'brandVscode', label: 'VS Code' },
  { value: 'brandFigma', label: 'Figma' },
] as const satisfies ReadonlyArray<{ value: AppIconKey; label: string }>;

const legacyMaterialToAppIcon: Record<string, AppIconKey> = {
  add: 'add',
  add_box: 'addBox',
  add_circle: 'add',
  add_photo_alternate: 'photoPlus',
  arrow_back: 'arrowBack',
  arrow_forward: 'arrowForward',
  auto_awesome: 'sparkles',
  bolt: 'bolt',
  close: 'close',
  code: 'code',
  dashboard: 'dashboard',
  database: 'database',
  delete: 'trash',
  download: 'download',
  drag_indicator: 'drag',
  edit: 'edit',
  expand_more: 'chevronDown',
  folder_special: 'folder',
  help: 'help',
  height: 'spacer',
  image: 'image',
  inbox: 'inbox',
  inventory_2: 'archive',
  javascript: 'brandJavascript',
  layers: 'layers',
  location_on: 'mapPin',
  lock: 'lock',
  logout: 'logout',
  mail: 'mail',
  menu: 'menu',
  mongodb: 'brandMongodb',
  nextjs: 'brandNextjs',
  nodejs: 'brandNodejs',
  notes: 'notes',
  notifications: 'notifications',
  open_in_new: 'externalLink',
  person: 'user',
  github: 'brandGithub',
  'github.com': 'brandGithub',
  php: 'brandPhp',
  postgres: 'database',
  postgresql: 'database',
  publish: 'publish',
  python: 'brandPython',
  react: 'brandReact',
  reply: 'reply',
  search: 'search',
  settings: 'settings',
  smart_button: 'button',
  supabase: 'brandSupabase',
  tailwind: 'brandTailwind',
  terminal: 'terminal',
  title: 'title',
  typescript: 'brandTypescript',
  upload: 'upload',
  vue: 'brandVue',
  'vue.js': 'brandVue',
  laravel: 'brandLaravel',
  verified: 'verified',
  visibility_off: 'eyeOff',
  warning: 'warning',
  workspace_premium: 'certificate',
};

export function resolveAppIconKey(rawIcon: string | null | undefined, fallback: AppIconKey = 'terminal'): AppIconKey {
  if (!rawIcon) return fallback;

  const trimmed = rawIcon.trim();
  if (!trimmed) return fallback;

  if (trimmed in appIconRegistry) {
    return trimmed as AppIconKey;
  }

  return legacyMaterialToAppIcon[trimmed.toLowerCase()] || fallback;
}

const techIconHoverColors: Partial<Record<AppIconKey, string>> = {
  brandReact: '#61DAFB',
  brandNextjs: '#FFFFFF',
  brandNodejs: '#68A063',
  brandTypescript: '#3178C6',
  brandJavascript: '#F7DF1E',
  brandTailwind: '#38BDF8',
  brandMongodb: '#47A248',
  database: '#7C3AED',
  brandDocker: '#2496ED',
  brandGit: '#F05032',
  brandGithub: '#181717',
  brandSupabase: '#3ECF8E',
  brandMysql: '#4479A1',
  brandPython: '#3776AB',
  brandHtml5: '#E34F26',
  brandCss3: '#1572B6',
  brandOpenai: '#10A37F',
  brandVscode: '#007ACC',
  brandFigma: '#A259FF',
  brandPhp: '#777BB4',
  brandLaravel: '#FF2D20',
  brandVue: '#42B883',
};

export function resolveTechIconHoverColor(rawIcon: string | null | undefined): string {
  const key = resolveAppIconKey(rawIcon, 'terminal');
  return techIconHoverColors[key] || '#c3c0ff';
}
